### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'replace'

### ISSUE THREAD

**Issue by archana433** [guigolab/ggsashimi#36]
used this command - ./sashimi-plot.py -b wt_chr2.bam -g Mus_musculus.GRCm38.99.gtf -o wt_1_

Traceback (most recent call last):
  File "./sashimi-plot.py", line 578, in <module>
    a, junctions = read_bam(bam, args.coordinates, args.strand)
  File "./sashimi-plot.py", line 125, in read_bam
    _, start, end = parse_coordinates(c)
  File "./sashimi-plot.py", line 67, in parse_coordinates
    c = c.replace(",", "")
AttributeError: 'NoneType' object has no attribute 'replace'

**Comment by emi80** [comment]
Hi @archana433,

you always need to specify a region of interest using the `-c` command line option. 
Though, we might set the parameter as required and definitely need to give a more informative error message.

Thanks for reporting this.

**Comment by archana433** [comment]
Thank you, 
now i am getting this error- 
Traceback (most recent call last):
  File "./sashimi-plot.py", line 612, in <module>
    transcripts, exons = read_gtf(args.gtf, args.coordinates)
  File "./sashimi-plot.py", line 284, in read_gtf
    transcript_id = d["transcript_id"]
KeyError: 'transcript_id'
