### ISSUE TITLE
ValueError: invalid contig `chr1`

### ISSUE THREAD

**Issue by patchthr33** [guigolab/ggsashimi#73]
Hello, I am currently trying to generate sashimi plots and when I run the following script 
`./ggsashimi.py -b sample_list.tsv -c chr1:15489401-15526790 -M 10 -C 3 -O 3 -A median --alpha 1 -F tiff -R 350 --base-size=16 --height=3 --width=18 --fix-y-scale`

I receive the following error. I am unsure of why this error is occurring and I cant seem to find an answer.

`Traceback (most recent call last):
  File "./ggsashimi.py", line 673, in <module>
    a, junctions = read_bam(bam, args.coordinates, args.strand)
  File "./ggsashimi.py", line 174, in read_bam
    for read in samfile.fetch(chr, start, end):
  File "pysam/libcalignmentfile.pyx", line 1082, in pysam.libcalignmentfile.AlignmentFile.fetch
  File "pysam/libchtslib.pyx", line 685, in pysam.libchtslib.HTSFile.parse_region
ValueError: invalid contig 'chr1'`

I greatly appreciate any help that can be provided

**Comment by OnkarMulay** [comment]
Hi,

I get the same error what to do?

Command:
python2 /g/data/zq45/onkar/ggsashimi/ggsashimi.py -b /g/data/zq45/onkar/ggsashimi/input_bams.tsv -c chr10:27040584-27048100 -
M 10 -C 3 -O 3 -A mean --alpha 1 -F tiff -R 350 --base-size=16 --height=3 --width
=18 --fix-y-scale

Traceback (most recent call last):
  File "/g/data/zq45/onkar/ggsashimi/ggsashimi.py", line 677, in <module>
    a, junctions = read_bam(bam, args.coordinates, args.strand)
  File "/g/data/zq45/onkar/ggsashimi/ggsashimi.py", line 174, in read_bam
    for read in samfile.fetch(chr, start, end):
  File "pysam/libcalignmentfile.pyx", line 1082, in pysam.libcalignmentfile.AlignmentFile.fetch
  File "pysam/libchtslib.pyx", line 685, in pysam.libchtslib.HTSFile.parse_region
ValueError: invalid contig `chr10`

**Comment by delongmeng** [comment]
Same error! Can anyone help?
```
docker run -w $PWD -v $PWD:$PWD guigolab/ggsashimi -b input_bams.tsv -c chr7:140426116-140439612 -g annotation.gtf
Traceback (most recent call last):
  File "/ggsashimi.py", line 677, in <module>
    a, junctions = read_bam(bam, args.coordinates, args.strand)
  File "/ggsashimi.py", line 174, in read_bam
    for read in samfile.fetch(chr, start, end):
  File "pysam/libcalignmentfile.pyx", line 1091, in pysam.libcalignmentfile.AlignmentFile.fetch
  File "pysam/libchtslib.pyx", line 685, in pysam.libchtslib.HTSFile.parse_region
ValueError: invalid contig `chr7`
```

**Comment by luisafmc** [comment]
Hi!
I know this error was closed. However, I realized that you must saw how the chr has been called in your Bam file. I've faced the same error and I realized that the chr in my Bam file is just "1 or X or Y" instead of "chr1, chrX or chrY". You can see this info by using:

`samtools view input.bam   `

I ran STAR mapping and for some reason, the names are in these ways. 

I hope it could help somebody else!
