### ISSUE TITLE
 invalid contig issue

### ISSUE THREAD

**Issue by OnkarMulay** [guigolab/ggsashimi#78]
Hi,

I get an invalid contig issue. With or without gtf :( 

Command:
python2 /g/data/zq45/onkar/ggsashimi/ggsashimi.py -b /g/data/zq45/onkar/ggsashimi/input_bams.tsv -c chr10:27040584-27048100 -M 10 -C 3 -O 3 -A mean --alpha 1 -F tiff -R 350 --base-size=16 --height=3 --width=18 --fix-y-scale

Traceback (most recent call last):
File "/g/data/zq45/onkar/ggsashimi/ggsashimi.py", line 677, in
a, junctions = read_bam(bam, args.coordinates, args.strand)
File "/g/data/zq45/onkar/ggsashimi/ggsashimi.py", line 174, in read_bam
for read in samfile.fetch(chr, start, end):
File "pysam/libcalignmentfile.pyx", line 1082, in pysam.libcalignmentfile.AlignmentFile.fetch
File "pysam/libchtslib.pyx", line 685, in pysam.libchtslib.HTSFile.parse_region
ValueError: invalid contig chr10

**Comment by dgarrimar** [comment]
Hi @OnkarMulay, could you please provide a small sample dataset to help us guess what happens? It may be that chromosome names differ beteween bam files and coordinates provided?
