### ISSUE TITLE
Error running docker latest docker image (v.1.1.0)

### ISSUE THREAD

**Issue by PedroBarbosa** [guigolab/ggsashimi#80]
Hi,

I've been using your package with success in the past, but since this last update i get the following error when running:

```
shifter --image=guigolab/ggsashimi:latest /ggsashimi.py --help 

Traceback (most recent call last):
  File "/ggsashimi.py", line 8, in <module>
    import pysam
  File "/usr/local/lib/python3.8/dist-packages/pysam/__init__.py", line 5, in <module>
    from pysam.libchtslib import *
ImportError: libz-a147dcb0.so.1.2.3: cannot open shared object file: No such file or directory
```

When i enter in the interactive mode, i run without any problems:
```
shifter -it --image=guigolab/ggsashimi:latest bash
/gsashimi.py --help 

usage: ggsashimi.py [-h] -b BAM -c COORDINATES [-o OUT_PREFIX] [-S OUT_STRAND]
                    [-M MIN_COVERAGE] [-j JUNCTIONS_BED] [-g GTF] [-s STRAND]
                    [--shrink] [-O OVERLAY] [-A AGGR] [-C COLOR_FACTOR]
                    [--alpha ALPHA] [-P PALETTE] [-L LABELS] [--fix-y-scale]
                    [--height HEIGHT] [--ann-height ANN_HEIGHT]
                    [--width WIDTH] [--base-size BASE_SIZE] [-F OUT_FORMAT]
                    [-R OUT_RESOLUTION] [--debug-info] [--version]

Create sashimi plot for a given genomic region
```

Any possibility to take a look into this ?
Best regards,
Pedro

**Comment by ilee-ui** [comment]
I had the same problem. Have you solved it?
```
docker run guigolab/ggsashimi --help
Traceback (most recent call last):
  File "/ggsashimi.py", line 8, in <module>
    import pysam
  File "/usr/local/lib/python3.8/dist-packages/pysam/__init__.py", line 5, in <module>
    from pysam.libchtslib import *
ImportError: liblzma-75668d9c.so.0.0.0: cannot open shared object file: No such file or directory

```
Thanks

**Comment by emi80** [comment]
Hi @PedroBarbosa and @ilee-ui, thanks for reporting and follow up with this.

I will shortly make a patch release that fixes the problem.

Best,
Emilio
