### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by gurpreet-bioinfo** [guigolab/ggsashimi#82]
Hi @dgarrimar 
I am keep on getting the same error as here: [https://github.com/guigolab/ggsashimi/issues/32](url)

I checked my `input_bams.tsv` file but still the error persists with `bam = get_bam_path(f, line_sp[1])`

```
Traceback (most recent call last):
  File "ggsashimi.py", line 674, in <module>
    for id, bam, overlay_level, color_level, label_text in read_bam_input(args.bam, args.overlay, args.color_factor, args.labels):
  File "ggsashimi.py", line 215, in read_bam_input
    bam = get_bam_path(f, line_sp[1])
IndexError: list index out of range
```

Any thoughts?
Thanks.

**Comment by gurpreet-bioinfo** [comment]
@dgarrimar  My command:
`python ggsashimi.py -b input_bams.tsv -c chr17:27756766-27800529 -g genes.gtf -o ggsashimi -C 3 -O 3 --alpha 0.25 --base-size=20 --ann-height=4 --height=3 --width=18 -P palette.txt -F png `

I changed from `python` to `python3 `and now getting following error with `overlay_level = line_sp[overlay-1] if overlay else None` :

```
Traceback (most recent call last):
  File "ggsashimi.py", line 674, in <module>
    for id, bam, overlay_level, color_level, label_text in read_bam_input(args.bam, args.overlay, args.color_factor, args.labels):
  File "/ggsashimi.py", line 216, in read_bam_input
    overlay_level = line_sp[overlay-1] if overlay else None
IndexError: list index out of range
```

**Comment by gurpreet-bioinfo** [comment]
@dgarrimar Thanks for the reply. I was able to sort this issue.
